# Generated by Django 5.2.13 on 2026-04-08 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecargo', '0002_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_mode', models.CharField(choices=[('exchange', 'Exchange'), ('selected', 'To Selected')], default='exchange', max_length=20)),
                ('time_to_submit_offers', models.DateTimeField(blank=True, null=True)),
                ('contacts', models.CharField(blank=True, max_length=255)),
                ('buy_now', models.BooleanField(default=False)),
                ('schedule_publication', models.BooleanField(default=False)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('CZK', 'CZK')], default='EUR', max_length=5)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vehicle_size', models.CharField(blank=True, choices=[('semi', 'With Semi-Trailer'), ('solo', 'Solo'), ('van', 'Van'), ('double', 'With Double Trailer')], max_length=20)),
                ('body_type', models.CharField(blank=True, choices=[('curtainsider', 'Curtainsider'), ('tautliner', 'Tautliner'), ('flatbed', 'Flatbed'), ('box', 'Box / Closed'), ('refrigerated', 'Refrigerated'), ('tanker', 'Tanker'), ('lowloader', 'Low Loader'), ('tipper', 'Tipper'), ('container', 'Container'), ('other', 'Other')], max_length=30)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Tonnes', max_digits=8, null=True)),
                ('load_meters', models.DecimalField(blank=True, decimal_places=2, help_text='LDM', max_digits=6, null=True)),
                ('load_type', models.CharField(choices=[('FTL', 'FTL - Full Truck Load'), ('LTL', 'LTL - Less than Truck Load')], default='FTL', max_length=3)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('stackable', models.BooleanField(default=False)),
                ('to_exchange', models.BooleanField(default=False)),
                ('additional_description', models.TextField(blank=True, max_length=2000)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('pickup', 'Loading'), ('delivery', 'Unloading'), ('intermediate', 'Intermediate Stop')], max_length=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('full_address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('is_range', models.BooleanField(default=False)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='ecargo.load')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
