# Generated by Django 5.2.13 on 2026-04-09 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecargo', '0003_load_loadlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadlocation',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='load',
            old_name='price',
            new_name='price_per_mile',
        ),
        migrations.RemoveField(
            model_name='load',
            name='price_per_km',
        ),
        migrations.RemoveField(
            model_name='load',
            name='total_distance_km',
        ),
        migrations.RemoveField(
            model_name='loadlocation',
            name='order',
        ),
        migrations.AddField(
            model_name='load',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='payment_deadline_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment deadline in days, e.g. 30, 40', null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('CZK', 'CZK')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='loadlocation',
            name='location_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='loadlocation',
            constraint=models.UniqueConstraint(fields=('load', 'location_type'), name='unique_pickup_delivery_per_load'),
        ),
    ]
