# Generated by Django 5.2.13 on 2026-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecargo', '0004_alter_loadlocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='loadlocation',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='load',
            name='payment_deadline_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
